Update auto-deploy-use-selfhosted-runner.yml

diff --git a/.github/workflows/auto-deploy-use-selfhosted-runner.yml b/.github/workflows/auto-deploy-use-selfhosted-runner.yml
--- a/.github/workflows/auto-deploy-use-selfhosted-runner.yml
+++ b/.github/workflows/auto-deploy-use-selfhosted-runner.yml
@@ -337,8 +337,10 @@ jobs:
           echo "Copied files to $DEST_PATH." >> "$LOG_FILE"
 
           # A.Kitagawa updated temporary on 2026/05/05 start
-          find $DEST_PATH -type d -print0 | xargs -0 setfacl -m m:rwx,d:m:rwx
-          find $DEST_PATH -type f -print0 | xargs -0 setfacl -m m:rw-
+          if ! find $DEST_PATH -type d -print0 | xargs -0 -r setfacl -m m:rwx,d:m:rwx || ! find $DEST_PATH -type f -print0 | xargs -0 -r setfacl -m m:rw-; then
+            echo "Error: failed to change mask."
+            exit 1
+          fi
           # A.Kitagawa updated temporary on 2026/05/05 end
 
           # 6. 初回配信時のみ、配送先ルートに .Rprofile.org を作成する
